# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-29 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_DM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='location_to',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='\u8f6c\u53d1\u53bb\u5411'),
        ),
        migrations.AlterField(
            model_name='record',
            name='opinion_leader',
            field=models.CharField(default='\u65e0', max_length=100, verbose_name='\u9886\u5bfc\u610f\u89c1'),
        ),
    ]
