# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_DM', '0003_auto_20180530_1511'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': '\u516c\u6587\u6587\u6863\u6d41\u8f6c\u4fe1\u606f', 'verbose_name_plural': '\u516c\u6587\u6587\u6863\u6d41\u8f6c\u4fe1\u606f'},
        ),
    ]
