# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_DM', '0004_auto_20180616_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='time_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u622a\u81f3\u65f6\u95f4'),
        ),
    ]
