# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_DM', '0005_document_time_expired'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='flag_finished',
            field=models.BooleanField(default=False, verbose_name='\u662f\u5426\u529e\u7ed3'),
        ),
        migrations.AlterField(
            model_name='document',
            name='time_expired',
            field=models.DateTimeField(blank=True, null=True, verbose_name='\u529e\u7ed3\u65f6\u95f4'),
        ),
    ]
