# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-16 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UCAS_DM', '0006_auto_20180616_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='time_expired',
            field=models.DateTimeField(verbose_name='\u529e\u7ed3\u65f6\u95f4'),
        ),
    ]
